USE [DBO_PACTO]
GO

DROP PROCEDURE [dbo].[sp_ObterDocumentoPorKey]

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_ObterDocumentoPorKey](
	@DocumentoKey uniqueidentifier)	
AS

BEGIN	
	SET NOCOUNT ON;

SELECT 
    TB_DOCUMENTO.[COD_DOCUMENTO] AS Id,
    TB_DOCUMENTO.[KEY_DOCUMENTO] AS [Key],                    
    TB_DOCUMENTO.[TXT_NOME] AS Nome,                    
    TB_DOCUMENTO.[TXT_DESCRICAO] AS Descricao,                    
    TB_DOCUMENTO.[DAT_INC] AS DataCadastro,
    TB_DOCUMENTO.[IND_ORDEM_ASSINATURA] AS HabilitadoOrdemAssinatura,
    TB_DOCUMENTO.[DAT_PRAZO_ASSINATURA] AS DataPrazoFinalizacao,   
    TB_DOCUMENTO.[IND_RECEBER_NOTIFICACAO] AS HabilitadoNotificacao,
    TB_DOCUMENTO.[COD_USUARIO] AS IdProprietario,
    TB_DOCUMENTO.[TXT_NOME_USUARIO] AS NomeProprietario,
    TB_DOCUMENTO.[TXT_ARQUIVO] AS NomeArquivo,
    TB_DOCUMENTO.[COD_TIPO_FINALIZACAO] AS IdTipoFinalizacao,
    TB_DOCUMENTO.[COD_STATUS_DOCUMENTO] AS IdStatus,
    TB_DOCUMENTO_ASSINANTE.[COD_DOCUMENTO_ASSINANTE] AS Id,
    TB_DOCUMENTO_ASSINANTE.[COD_DOCUMENTO] AS IdDocumento,
    TB_DOCUMENTO_ASSINANTE.[COD_ASSINANTE] AS IdAssinante,
    TB_DOCUMENTO_ASSINANTE.[COD_STATUS_ASSINATURA] AS IdStatus,
    TB_DOCUMENTO_ASSINANTE.[COD_TIPO_IDENTIFICACAO] AS IdTipoIdentificacao,
    TB_DOCUMENTO_ASSINANTE.[KEY_DOCUMENTO_ASSINANTE] AS [Key],
    TB_DOCUMENTO_ASSINANTE.[INT_ORDEM_ASSINATURA] AS Ordem,
    TB_DOCUMENTO_ASSINANTE.[TXT_NOME_ASSINANTE] AS NomeAssinante,
    TB_DOCUMENTO_ASSINANTE.[TXT_IDENTIFICACAO] AS Identificacao,
    TB_DOCUMENTO_ASSINANTE.[TXT_QUALIFICACAO] AS Qualificacao,
    TB_DOCUMENTO_ASSINANTE.[DAT_PRAZO_ASSINATURA] AS DataLimiteAssinatura,
    TB_DOCUMENTO_ASSINANTE.[DAT_ASSINATURA_ELETRONICA] AS DataEfetivacaoAssinatura,
    TB_DOCUMENTO_ASSINANTE.[DAT_DECLINIO] AS DataDeclinio,
    TB_DOCUMENTO_ASSINANTE.[TXT_MOTIVO_DECLINIO] AS JustificativaDeclinio,
    TB_DOCUMENTO_ASSINANTE.[IND_EXCLUIDO] AS Excluido,
    TB_DOCUMENTO_ASSINANTE.[TXT_JUSTIFICATIVA_EXCLUSAO] AS JustificativaExclusao,
    TB_TIPO_ASSINATURA.[COD_TIPO_ASSINATURA] AS Id,
    TB_TIPO_ASSINATURA.[TXT_NOME] AS Nome,
    StatusAssinatura.[COD_STATUS_ASSINATURA] AS Id,
    StatusAssinatura.[TXT_NOME] AS Nome,
    TB_TIPO_FINALIZACAO.[COD_TIPO_FINALIZACAO] AS Id,
    TB_TIPO_FINALIZACAO.[TXT_NOME] AS Nome,
    TB_TIPO_IDENTIFICACAO.[COD_TIPO_IDENTIFICACAO] AS Id,
    TB_TIPO_IDENTIFICACAO.[TXT_DESCRICAO] AS Descricao
FROM 
    TB_DOCUMENTO WITH (NOLOCK)
INNER JOIN
    TB_DOCUMENTO_ASSINANTE WITH (NOLOCK) ON TB_DOCUMENTO_ASSINANTE.[COD_DOCUMENTO] = TB_DOCUMENTO.[COD_DOCUMENTO]
LEFT JOIN
    TB_TIPO_ASSINATURA WITH (NOLOCK) ON TB_TIPO_ASSINATURA.[COD_TIPO_ASSINATURA] = TB_DOCUMENTO.[COD_TIPO_ASSINATURA]
LEFT JOIN
    TB_STATUS_ASSINATURA WITH (NOLOCK) ON TB_STATUS_ASSINATURA.[COD_STATUS_ASSINATURA] = TB_DOCUMENTO.[COD_STATUS_DOCUMENTO]
LEFT JOIN
    TB_TIPO_FINALIZACAO WITH (NOLOCK) ON TB_TIPO_FINALIZACAO.[COD_TIPO_FINALIZACAO] = TB_DOCUMENTO.[COD_TIPO_FINALIZACAO]
LEFT JOIN
    TB_TIPO_IDENTIFICACAO WITH (NOLOCK) ON TB_TIPO_IDENTIFICACAO.[COD_TIPO_IDENTIFICACAO] = TB_DOCUMENTO_ASSINANTE.[COD_TIPO_IDENTIFICACAO]
LEFT JOIN
    TB_STATUS_ASSINATURA AS StatusAssinatura WITH (NOLOCK) ON StatusAssinatura.[COD_STATUS_ASSINATURA] = TB_DOCUMENTO_ASSINANTE.[COD_STATUS_ASSINATURA]
WHERE
    TB_DOCUMENTO.[KEY_DOCUMENTO] = @DocumentoKey
END
GO

